name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go for use with actions
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports
    - name: Set env with list of directories in repo containin go code
      run: echo GO_USR_DIRS=$(go list -f {{.Dir}} ./... | grep -E -v "/gen-go/|/vendor/") >> $GITHUB_ENV
    - name: Run goimports check
      run: test -z "`for d in $GO_USR_DIRS; do goimports -d $d/*.go | tee /dev/stderr; done`"
    - name: Check Docker Version
      run: docker --version
    - name: Install Latest Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update -y && apt-get install docker-ce=18.06.2~ce~3-0~ubuntu
    - name: Check Docker Version
      run: docker --version

    - name: Create aurora/mesos docker cluster
      run: docker-compose up -d
    - name: Run tests
      run: go test -timeout 35m -race -coverprofile=coverage.txt -covermode=atomic -v github.com/aurora-scheduler/gorealis/v2
        
